In [37]:
import copy
import matplotlib.pyplot as plt
import numpy as np

In [38]:
A = np.array([     
        [2, -1, 1, 1],
        [1, 2,-1, -1],
        [-1, 2, 2, 2],
        [ 1,-1, 2, 1]    
    ], dtype=np.dtype(float)) 
b = np.array([6, 3, 14, 8], dtype=np.dtype(float))

In [39]:
def augmented_to_ref(A, b):    
    ### START CODE HERE ###
    # stack horizontally matrix A and vector b, which needs to be reshaped as a vector (4, 1)
    A_system = np.hstack((A, b.reshape(4,1)))
    
    A_ref = A_system.copy()
    # swap row 0 and row 1 of matrix A_system (remember that indexing in NumPy array starts from 0)
    A_ref[0], A_ref[1] = A_ref[1], A_ref[0] 
    
    # multiply row 0 of the new matrix A_ref by -2 and add it to the row 1
    A_ref[1] = -2* A_ref[0] + A_ref[1] 
    
    # add row 0 of the new matrix A_ref to the row 2, replacing row 2
    A_ref[2] = A_ref[0] + A_ref[2]
    
    # multiply row 0 of the new matrix A_ref by -1 and add it to the row 3
    A_ref[3] = -1 * A_ref[0] + A_ref[3]
    
    # add row 2 of the new matrix A_ref to the row 3, replacing row 3
    A_ref[3] = A_ref[2] + A_ref[3]
    
    # swap row 1 and 3 of the new matrix A_ref
    A_ref[1], A_ref[3] = A_ref[3], A_ref[1]
    
    # add row 2 of the new matrix A_ref to the row 3, replacing row 3
    A_ref[3] = A_ref[2] + A_ref[3] 
    
    # multiply row 1 of the new matrix A_ref by -4 and add it to the row 2
    A_ref[2] = -4*A_ref[1] + A_ref[2]
    
    # add row 1 of the new matrix A_ref to the row 3, replacing row 3
    A_ref[3] = A_ref[1] + A_ref[3]
    
    # multiply row 3 of the new matrix A_ref by 2 and add it to the row 2
    A_ref[2] =  2* A_ref[3] + A_ref[2]
    
    # multiply row 2 of the new matrix A_ref by -8 and add it to the row 3
#   A_ref[3] = -8*A_ref[2] + A_ref[3]
    
    # multiply row 3 of the new matrix A_ref by -1/17
#    A_ref[3] = -1/17 * A_ref[3]
    ### END CODE HERE ###
    
    return A_ref

A_ref = augmented_to_ref(A, b)

print(A_ref)

[[ 1.  2. -1. -1.  3.]
 [ 0.  1.  4.  3. 22.]
 [ 0. 12.  3.  3. 51.]
 [ 0.  6.  9.  7. 61.]]


In [40]:
ori = [1,2,3,4,[5,6],7]
sha = copy.copy(ori)
dee = copy.deepcopy(ori)
print(ori)
print(sha)
print(dee)

[1, 2, 3, 4, [5, 6], 7]
[1, 2, 3, 4, [5, 6], 7]
[1, 2, 3, 4, [5, 6], 7]


In [41]:
ori[2] = 10
print(ori)
print(sha)
print(dee)

[1, 2, 10, 4, [5, 6], 7]
[1, 2, 3, 4, [5, 6], 7]
[1, 2, 3, 4, [5, 6], 7]


In [42]:
w1 = np.array([[ 7.7875534 ,  7.99703637],
         [ 7.57723684, -8.43113562],
         [ 6.49492033,  2.8117102 ],
         [ 9.14944707, -2.67920217],
         [-0.17012221,  9.35646387]])
b1 =np.array([[-0.03976475],
         [ 0.05653709],
         [-0.33272316],
         [ 0.23410297],
         [ 0.06653469]])

w2 =  np.array([-8.6697934 ,  9.38368566,  3.88897654, -3.50740181, 10.19257937])

b2 = np.array([-0.01902426])

inputt = np.array([[ 1.62434536, -0.61175641, -0.52817175],
        [-1.07296862,  0.86540763, -2.3015387 ]])



z1=  np.dot(w1, inputt ) + b1

A1 = np.tanh(z1)

z2 = np.dot(w2,A1) + b2

A2 = 1 / (1 + np.exp(-z2))

A2

array([1.10469852e-04, 3.95806239e-04, 6.76490251e-01])

In [43]:
import math
a  = np.arange(1,61).reshape(3,20)
m = a.shape[1]
b = np.random.permutation(m)
shuffled = a[:,b]
print(a)
batch = 3
num_batch = math.floor(m/batch)
print(num_batch)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60]]
6


In [45]:
mini_batch = []
for i in range(0, num_batch):
    mini_batchX = shuffled[:, i*batch:(i+1)*batch]
    mini_batch.append(mini_batchX)
if m%batch != 0:
    mini_batchX = shuffled[:, int(m/batch)*batch:]
    mini_batch.append(mini_batchX)
print(mini_batch)
for i in range(0,len(mini_batch)):
    print(mini_batch[i].shape)
    

[array([[18, 11, 13],
       [38, 31, 33],
       [58, 51, 53]]), array([[10, 20, 19],
       [30, 40, 39],
       [50, 60, 59]]), array([[ 9,  1,  6],
       [29, 21, 26],
       [49, 41, 46]]), array([[12, 16,  8],
       [32, 36, 28],
       [52, 56, 48]]), array([[ 7,  4, 14],
       [27, 24, 34],
       [47, 44, 54]]), array([[ 3, 17,  2],
       [23, 37, 22],
       [43, 57, 42]]), array([[ 5, 15],
       [25, 35],
       [45, 55]])]
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 2)


In [47]:
l = [1,2,4,5]
for i in range(len(l)):
    print(i)

0
1
2
3
