In [1]:
import numpy as np

w1 = np.random.randn(5,2)
w2 = np.random.randn(2,5)

print(w1)
print(w2)

[[-1.04149372 -0.9792652 ]
 [-0.63824462  0.01590575]
 [ 0.94171721  0.39644919]
 [-0.58437126 -0.54827689]
 [ 1.43615319 -1.35263082]]
[[-1.30620053 -2.39694748  0.22377064 -0.29426649 -0.04960433]
 [ 1.9125055   0.43875692 -0.44282038  1.0763097   1.52367781]]


In [2]:
Sum_w1 = np.sum(np.square(w1))
Sum_w2 = np.sum(np.square(w2))
print(Sum_w1,Sum_w2)

8.029525374143931 15.116955172503388


In [3]:
b = np.random.randn(2,2)
print(b)
np.sum(np.square(b))

[[ 1.0879087   1.74468319]
 [ 1.08525556 -1.20602727]]


6.859746164420258

In [4]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
keep_prob = 0.8
A_WNP = np.mean(A)
d = np.random.random((A.shape[0],A.shape[1]))<keep_prob
A_N = A*d
A_WD = np.mean(A_N)
A_I = A_N/keep_prob
A_ID = np.mean(A_I)
print(A_N)
print(A_I)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1.25  2.5   3.75]
 [ 5.    6.25  7.5 ]
 [ 8.75 10.   11.25]]


In [5]:
print(A_WNP)
print(A_WD)
print(A_ID)

5.0
5.0
6.25


In [6]:
x = np.array([1,2,0,-1,2,0,1])
np.where(x<=0,0,1)

array([1, 1, 0, 0, 1, 0, 1])

In [7]:
x
np.int8(x>0)

array([1, 1, 0, 0, 1, 0, 1], dtype=int8)

In [8]:
layers_dims = [200, 20, 1]
parameters = {}
L= len(layers_dims)
for  l in range(1, L):
    parameters['W' + str(l)]= np.random.randn(layers_dims[l], layers_dims[l-1]) * np.sqrt(1/layers_dims[l-1])
    parameters['b' + str(l)] = np.zeros((layers_dims[l],1))
    
W1 = parameters['W1']
W2 = parameters['W2']
b1 = parameters['b1']
b2 = parameters['b2']
print(W1.shape)
print(W2.shape)
print(b1.shape)
print(b2.shape)



(20, 200)
(1, 20)
(20, 1)
(1, 1)


In [9]:
a = np.random.randn(20,5)
b = np.random.randn(5,10)
c = np.multiply(a,b)
c.shape

ValueError: operands could not be broadcast together with shapes (20,5) (5,10) 

In [ ]:
X = np.array([1,2,3,4,5,6,7,8,9,10])
W1 = np.random.randn(10,5)
b1 = np.random.randn(5,1)

Z1 = np.dot(W1.T,X)
print(Z1)
A1 = np.maximum(0,Z1)
print(A1)

A2 = np.int64(Z1>0)
print(A2)
A3 = np.int64(A1>0)
print(A3)

In [ ]:
n = np.array([1,2,3,4,5,6,7,8,9,10])
np.maximum(0,n)

In [ ]:
def data():
    s = 'Hello'
    print(s + 'world')

data()