In [1]:
import  numpy as np
import time
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()
print(c)
print('vectorization version: ' + str(1000*(toc-tic)) + ' ms')

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()
print(c)
print('for loop: ' + str(1000*(toc-tic)) + ' ms')

250297.6748004904
vectorization version: 46.892642974853516 ms
250297.67480049666
for loop: 1205.686092376709 ms


Vectors and Matrix

In [2]:
A = np.array([[56, 0, 44, 68],
              [1.2, 104, 52, 8],
              [1.8, 135, 99, 0.8]])

cal = A.sum(axis=0)
print(cal)
per = 100*A/cal.reshape(1,4)
per
 

[ 59.  239.  195.   76.8]


array([[94.91525424,  0.        , 22.56410256, 88.54166667],
       [ 2.03389831, 43.51464435, 26.66666667, 10.41666667],
       [ 3.05084746, 56.48535565, 50.76923077,  1.04166667]])

In [3]:
a = np.random.randn(12288,150)
b = np.random.randn(150,45) 

c = np.dot(a,b)
c.shape

(12288, 45)

In [4]:
a=np.array([[2,1],[1,3]])
print(np.dot(a,a))

[[ 5  5]
 [ 5 10]]


In [5]:
x=np.array([[[1],[2]],[[3],[4]]])
x

array([[[1],
        [2]],

       [[3],
        [4]]])

In [6]:
x = np.array([[0, 3, 4],
              [1, 6, 4]])
x_norm = np.linalg.norm(x, axis=1, ord=2)
x_norm = x_norm.reshape(-1,1)
x_norm.shape, x_norm

((2, 1),
 array([[5.        ],
        [7.28010989]]))

In [7]:
x = x.astype('float64')
x /= x_norm
import numpy as np
import time
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

tim = time.process_time()
dot = 0
for i in range(len(x1)):
    dot += x1[i]*x2[i]

toc = time.process_time()

x

array([[0.        , 0.6       , 0.8       ],
       [0.13736056, 0.82416338, 0.54944226]])

In [8]:
import numpy as np
import time
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

tim = time.process_time()
dot = 0
for i in range(len(x1)):
    dot += x1[i]*x2[i]

toc = time.process_time()
tt = 1000*(toc-tim)
print(f' dot: {dot}  computation time {tt} ms')
    

 dot: 278  computation time 0.0 ms


In [9]:
outer = np.zeros((len(x1), len(x2)))

tim = time.process_time()
for i in range(len(x1)):
    for j in range(len(x2)):
        outer[i,j] = x1[i]*x2[j]
        
toc = time.process_time()
tt = 1000*(toc-tim)
print(f' outer: {outer}  "computation time: {1000*toc-1000*tim}')

 outer: [[81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [63. 14. 14. 63.  0. 63. 14. 35.  0.  0. 63. 14. 35.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]  "computation time: 0.0


In [10]:
W = np.random.randn(3, len(x1))
print(W)
gdot = np.zeros(W.shape[0])
print(gdot)
tim = time.time()

for i in range(W.shape[0]):
    for j in range(len(x1)):
        gdot[i] += W[i,j]*x1[j]

toc = time.time()
print(f' gdot: {gdot} computation time {toc-tim}')

[[ 0.60283189  1.22276337  0.56243825  0.94257425  0.55386149  1.06943786
  -0.36745966  0.67670052  1.1975321  -0.02842033 -2.09318481 -0.16409329
  -1.95139709 -1.2270863   0.10196978]
 [ 0.58354942 -0.42418447  0.40111264  0.30227261  0.74813637  0.06181164
   0.40483636 -1.16111971 -0.53455186 -0.38500611 -1.58226615  0.1134466
   0.38466929 -0.05250529  1.01112586]
 [ 0.99891562 -0.06365836  0.79323801  0.33573168  0.78876057 -0.67073361
   1.40257485  0.23269103  0.73993524  1.47116733 -1.17200398 -0.44616654
   1.11527028  0.725074    1.4414141 ]]
[0. 0. 0.]
 gdot: [-12.59186364  -3.22415345   9.28283543] computation time 0.0


In [11]:
W

array([[ 0.60283189,  1.22276337,  0.56243825,  0.94257425,  0.55386149,
         1.06943786, -0.36745966,  0.67670052,  1.1975321 , -0.02842033,
        -2.09318481, -0.16409329, -1.95139709, -1.2270863 ,  0.10196978],
       [ 0.58354942, -0.42418447,  0.40111264,  0.30227261,  0.74813637,
         0.06181164,  0.40483636, -1.16111971, -0.53455186, -0.38500611,
        -1.58226615,  0.1134466 ,  0.38466929, -0.05250529,  1.01112586],
       [ 0.99891562, -0.06365836,  0.79323801,  0.33573168,  0.78876057,
        -0.67073361,  1.40257485,  0.23269103,  0.73993524,  1.47116733,
        -1.17200398, -0.44616654,  1.11527028,  0.725074  ,  1.4414141 ]])

In [14]:
x = [1,2,3,4]
w = np.random.randn(2, len(x))
print(w)
gdot = np.zeros(w.shape[0])
print(gdot)
tim = time.time()

for i in range(w.shape[0]):
    for j in range(len(x)):
        gdot[i] += w[i,j]*x[j]

toc = time.time()
print(f' gdot: {gdot} computation time {toc-tim}')

[[-0.06388283 -0.02310955 -0.68401432 -0.26530258]
 [-1.01088108 -0.62472804 -2.45377379 -1.27355243]]
[0. 0.]
 gdot: [ -3.22335522 -14.71586826] computation time 0.0
